export declare type stateName = ['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District Of Columbia', 'Federated States Of Micronesia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Marshall Islands', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Palau', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virgin Islands', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'];
export declare type statePostalCode = ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"];
export declare const statePostalToName: {
    AL: string;
    AK: string;
    AS: string;
    AZ: string;
    AR: string;
    CA: string;
    CO: string;
    CT: string;
    DE: string;
    DC: string;
    FM: string;
    FL: string;
    GA: string;
    GU: string;
    HI: string;
    ID: string;
    IL: string;
    IN: string;
    IA: string;
    KS: string;
    KY: string;
    LA: string;
    ME: string;
    MH: string;
    MD: string;
    MA: string;
    MI: string;
    MN: string;
    MS: string;
    MO: string;
    MT: string;
    NE: string;
    NV: string;
    NH: string;
    NJ: string;
    NM: string;
    NY: string;
    NC: string;
    ND: string;
    MP: string;
    OH: string;
    OK: string;
    OR: string;
    PW: string;
    PA: string;
    PR: string;
    RI: string;
    SC: string;
    SD: string;
    TN: string;
    TX: string;
    UT: string;
    VT: string;
    VI: string;
    VA: string;
    WA: string;
    WV: string;
    WI: string;
    WY: string;
};
export declare const stateNameToPostal: {
    Alabama: string;
    Alaska: string;
    'American Samoa': string;
    Arizona: string;
    Arkansas: string;
    California: string;
    Colorado: string;
    Connecticut: string;
    Delaware: string;
    'District Of Columbia': string;
    'Federated States Of Micronesia': string;
    Florida: string;
    Georgia: string;
    Guam: string;
    Hawaii: string;
    Idaho: string;
    Illinois: string;
    Indiana: string;
    Iowa: string;
    Kansas: string;
    Kentucky: string;
    Louisiana: string;
    Maine: string;
    'Marshall Islands': string;
    Maryland: string;
    Massachusetts: string;
    Michigan: string;
    Minnesota: string;
    Mississippi: string;
    Missouri: string;
    Montana: string;
    Nebraska: string;
    Nevada: string;
    'New Hampshire': string;
    'New Jersey': string;
    'New Mexico': string;
    'New York': string;
    'North Carolina': string;
    'North Dakota': string;
    'Northern Mariana Islands': string;
    Ohio: string;
    Oklahoma: string;
    Oregon: string;
    Palau: string;
    Pennsylvania: string;
    'Puerto Rico': string;
    'Rhode Island': string;
    'South Carolina': string;
    'South Dakota': string;
    Tennessee: string;
    Texas: string;
    Utah: string;
    Vermont: string;
    'Virgin Islands': string;
    Virginia: string;
    Washington: string;
    'West Virginia': string;
    Wisconsin: string;
    Wyoming: string;
};
//# sourceMappingURL=Constants.d.ts.map